package com.company;

/**
* com.company.arytmetykaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/dajevv/IdeaProjects/sri_corba/src/com/company/Arytmetyka.idl
* Sunday, May 31, 2020 11:53:22 AM CEST
*/

abstract public class arytmetykaHelper
{
  private static String  _id = "IDL:arytmetyka:1.0";

  public static void insert (org.omg.CORBA.Any a, arytmetyka that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static arytmetyka extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (arytmetykaHelper.id (), "arytmetyka");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static arytmetyka read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_arytmetykaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, arytmetyka value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static arytmetyka narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof arytmetyka)
      return (arytmetyka)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _arytmetykaStub stub = new _arytmetykaStub ();
      stub._set_delegate(delegate);
      return (arytmetyka) stub;
    }
  }

  public static arytmetyka unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof arytmetyka)
      return (arytmetyka)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _arytmetykaStub stub = new _arytmetykaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
