package com.company;


import arytmetykaPackage.DzieleniePrzezZero;

/**
 * arytmetykaOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from /Users/dajevv/IdeaProjects/sri_corba/src/com/company/Arytmetyka.idl
 * Sunday, May 31, 2020 11:53:22 AM CEST
 */

public interface arytmetykaOperations
{
    double s1 ();
    void s1 (double newS1);
    double s2 ();
    void s2 (double newS2);
    double wynik ();
    void wynik (double newWynik);
    void Suma ();
    void Roznica ();
    void Iloczyn ();
    void Iloraz () throws DzieleniePrzezZero, DzieleniePrzezZero;
} // interface arytmetykaOperations
