package com.company;


/**
 * arytmetyka.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from /Users/dajevv/IdeaProjects/sri_corba/src/com/company/Arytmetyka.idl
 * Sunday, May 31, 2020 11:53:22 AM CEST
 */

public interface arytmetyka extends arytmetykaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface arytmetyka
