package arytmetykaPackage;


/**
* arytmetykaPackage/DzieleniePrzezZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/dajevv/IdeaProjects/sri_corba/src/com/company/Arytmetyka.idl
* Sunday, May 31, 2020 11:53:22 AM CEST
*/

public final class DzieleniePrzezZero extends org.omg.CORBA.UserException
{

  public DzieleniePrzezZero ()
  {
    super(DzieleniePrzezZeroHelper.id());
  } // ctor


  public DzieleniePrzezZero (String $reason)
  {
    super(DzieleniePrzezZeroHelper.id() + "  " + $reason);
  } // ctor

} // class DzieleniePrzezZero
